import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import { ToastList } from "@/components/ui/ToastList";
import { PopupModal } from "@/components/ui/PopupModal";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
}) 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CodifyDev community",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}  antialiased bg-bgsecondary`}
      >
        <ReduxProvider>
            <ToastList/>
            <PopupModal/>
            {children}
        </ReduxProvider>
        
      </body>
    </html>
  );
}
