import { Geist, Geist_Mono, Poppins , Fira_Code} from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import { ToastList } from "@/components/ui/ToastList";
import { PopupModal } from "@/components/ui/PopupModal";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
}) 


const fira = Fira_Code({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-code',
}) 




export const metadata = {
  title: "CodifyDev community",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fira.variable}  font-fira antialiased bg-bgsecondary`}
      >
        <ReduxProvider>
            <ToastList/>
            <PopupModal/>
            {children}
        </ReduxProvider>
        
      </body>
    </html>
  );
}
