import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import { ToastList } from "@/components/ui/ToastList";
import { PopupModal } from "@/components/ui/PopupModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CodifyDev community",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-bgsecondary`}
      >
        <ReduxProvider>
            <ToastList/>
            <PopupModal/>
            {children}
        </ReduxProvider>
        
      </body>
    </html>
  );
}
